### ISSUE TITLE
Add in automated keyword analysis

### ISSUE THREAD

**Issue by adamlesniak** [adamlesniak/spens#1]
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ]  question about the decisions made in the repository
- [ ] question about how to use this project

- **Summary**

Currently keywords are defined in:

```
Expenses:
  Dining:
    Coffee:
      - 'STARBUCKS'
    Restaurant:
      - 'Uber Eats'
  Entertainment:
    Visits:
      - 'Museum of Modern Art'
  Subscriptions:
    Sport:
      - 'Gym'
    Entertainment:
      - 'Microsoft'
      - 'Google'
      - 'YouTube'
    Mobile:
      - 'Vodafone'
    Transport:
      - 'Bus'
  Shopping:
    Garden:
      - 'Woodies'
    Amazon:
      - 'Amazon'
  Donations:
    - 'Share the Meal'
```

https://github.com/adamlesniak/spens/blob/main/examples/sample_tokens_output.yml#L13-L39

Todo:

- Provide list of categories use by the app such as:

```
Income
Housing
Household Items
Food
Transportation
Medical/Health
Insurance
Home Services
Utilities
Groceries
Travel
Technology
```

Extract category from phrase such as:

`starbucks` should endup as `coffee shop`
`joes shop` should end up as `groceries`
`joes hardware shop` should end up as `diy`

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

- Endpoint to provide category based on phrase provided.
